In [15]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings 
warnings.filterwarnings("ignore")

In [ ]:
Integration = pd.read_csv('../../Data/study/03.통합_정규화.csv')
Integration.tail(17)
# 0.25가 젤 높은 군집이고 0.50이 두번째로 높은 군집 얘네는 별로 위험이 아님.
# 0.75가 세번째로 낮은 애들인데 뭐 거의 차이가 없다고 본다.
# 0.0 나오는 애들이 두번째로 낮은 애들인데 별 차이없음.
# 1 나오는 애들이 제일 낮은 지역임.
# 구분을 해보자. 0.25 = "위험없음", 0.50 = "양호", 0.75 = "소멸경고", 0.0 = "소멸위기", 1 = 소멸진행(근데 세종만 1임)


시점       시도       총인구      전출인구      출생아수   산부인과의원수   초등학생인원수  \
119  2013      경기도  0.910380  0.917273  0.987845  0.722646  0.960500   
120  2013    서울특별시  0.753220  0.815367  0.738139  1.000000  0.606175   
121  2013    부산광역시  0.255958  0.244302  0.219960  0.203562  0.201574   
122  2013     경상남도  0.241390  0.207586  0.252643  0.160305  0.240051   
123  2013    인천광역시  0.207265  0.215566  0.217549  0.170483  0.197767   
124  2013     경상북도  0.193710  0.160416  0.187705  0.139949  0.168028   
125  2013    대구광역시  0.178840  0.176790  0.162203  0.213740  0.169433   
126  2013     충청남도  0.144720  0.128457  0.155867  0.114504  0.143087   
127  2013     전라남도  0.134163  0.117580  0.127153  0.055980  0.120783   
128  2013     전라북도  0.131592  0.124568  0.119626  0.127226  0.128558   
129  2013     충청북도  0.109026  0.100428  0.111644  0.119593  0.107218   
130  2013      강원도  0.106736  0.101479  0.087815  0.081425  0.099779   
131  2013    대전광역시  0.106026  0.109410  0.115568  0.127226  0.113168   
132  2013    광주광역시  0.101524  0.108771  0.103378  0.109415  0.116652   
133  2013    울산광역시  0.077741  0.072153  0.090929  0.073791  0.078759   
134  2013  제주특별자치도  0.035450  0.033477  0.037523  0.048346  0.040838   
135  2013  세종특별자치시  0.000000  0.000000  0.000000  0.000000  0.000000   

     도매 및 소매업 신생  예금은행대출금액       예금액  cluster  
119     0.776750  0.339958  0.013776     0.25  
120     0.760073  0.635611  0.592332     0.50  
121     0.214863  0.103605  0.064875     0.75  
122     0.194295  0.075801  0.005956     0.75  
123     0.176916  0.082833  0.033262     0.75  
124     0.138730  0.035957  0.037772     0.75  
125     0.152346  0.061002  0.040335     0.75  
126     0.115372  0.033184  0.018502     0.00  
127     0.094549  0.018707  0.025479     0.00  
128     0.103780  0.027867  0.016236     0.00  
129     0.091822  0.020425  0.019279     0.00  
130     0.078589  0.014965  0.014253     0.00  
131     0.100671  0.029611  0.025211     0.00  
132     0.094325  0.028538  0.018596     0.00  
133     0.052201  0.023670  0.014746     0.00  
134     0.035189  0.006765  0.000000     0.00  
135     0.000000  0.000000  0.159209     1.00

In [33]:
Integration.loc[Integration['cluster'] == 0.25,"위험지수"] = '위험없음'
Integration.loc[Integration['cluster'] == 0.50,"위험지수"] = '양호'
Integration.loc[Integration['cluster'] == 0.75,"위험지수"] = '소멸경고'
Integration.loc[Integration['cluster'] == 0.00,"위험지수"] = '소멸위기'
Integration.loc[Integration['cluster'] == 1.00,"위험지수"] = '소멸진행'

In [34]:
Integration

시점       시도       총인구      전출인구      출생아수   산부인과의원수   초등학생인원수  \
0    2020      경기도  1.000000  1.000000  0.681823  0.669211  0.989493   
1    2020    서울특별시  0.717506  0.826711  0.412283  0.974555  0.527691   
2    2020    부산광역시  0.245759  0.249388  0.124101  0.165394  0.192010   
3    2020     경상남도  0.241871  0.205622  0.139806  0.145038  0.240947   
4    2020    인천광역시  0.212003  0.226092  0.132839  0.147583  0.196469   
..    ...      ...       ...       ...       ...       ...       ...   
131  2013    대전광역시  0.106026  0.109410  0.115568  0.127226  0.113168   
132  2013    광주광역시  0.101524  0.108771  0.103378  0.109415  0.116652   
133  2013    울산광역시  0.077741  0.072153  0.090929  0.073791  0.078759   
134  2013  제주특별자치도  0.035450  0.033477  0.037523  0.048346  0.040838   
135  2013  세종특별자치시  0.000000  0.000000  0.000000  0.000000  0.000000   

     도매 및 소매업 신생  예금은행대출금액       예금액  cluster  위험지수  
0       1.000000  0.576734  0.026286     0.25  위험없음  
1       0.783734  1.000000  1.000000     0.50    양호  
2       0.223664  0.179294  0.111145     0.75  소멸경고  
3       0.187088  0.111240  0.009975     0.75  소멸경고  
4       0.203894  0.137688  0.056396     0.75  소멸경고  
..           ...       ...       ...      ...   ...  
131     0.100671  0.029611  0.025211     0.00  소멸위기  
132     0.094325  0.028538  0.018596     0.00  소멸위기  
133     0.052201  0.023670  0.014746     0.00  소멸위기  
134     0.035189  0.006765  0.000000     0.00  소멸위기  
135     0.000000  0.000000  0.159209     1.00  소멸진행  

[136 rows x 12 columns]

In [35]:
Integration.columns

Index(['시점', '시도', '총인구', '전출인구', '출생아수', '산부인과의원수', '초등학생인원수', '도매 및 소매업 신생',
       '예금은행대출금액', '예금액', 'cluster', '위험지수'],
      dtype='object')

In [12]:
Integration.cluster.unique()
# 1 소멸진행, 0.75 소멸위기, 0.5 소멸위기 0.25 소멸양호 0 소멸무관

array([0.25, 0.5 , 0.75, 0.  , 1.  ])

In [4]:
# Feature
fish_input = Integration[['총인구', '전출인구', '출생아수', '산부인과의원수', '초등학생인원수', '도매 및 소매업 신생',
       '예금은행대출금액', '예금액']].to_numpy()
fish_input[:5]

array([[1.        , 1.        , 0.68182304, 0.6692112 , 0.98949327,
        1.        , 0.57673416, 0.02628575],
       [0.71750558, 0.82671082, 0.41228289, 0.97455471, 0.52769146,
        0.7837338 , 1.        , 1.        ],
       [0.24575928, 0.24938779, 0.1241013 , 0.1653944 , 0.19200974,
        0.22366428, 0.17929408, 0.11114458],
       [0.24187122, 0.20562189, 0.13980638, 0.14503817, 0.24094675,
        0.18708844, 0.1112403 , 0.00997535],
       [0.21200334, 0.22609175, 0.13283919, 0.1475827 , 0.19646917,
        0.20389356, 0.13768769, 0.05639608]])

In [36]:
# Target
fish_target = Integration['위험지수'].to_numpy()
fish_target

array(['위험없음', '양호', '소멸경고', '소멸경고', '소멸경고', '소멸경고', '소멸경고', '소멸위기',
       '소멸위기', '소멸위기', '소멸위기', '소멸위기', '소멸위기', '소멸위기', '소멸위기', '소멸위기',
       '소멸진행', '위험없음', '양호', '소멸경고', '소멸경고', '소멸경고', '소멸경고', '소멸경고',
       '소멸위기', '소멸위기', '소멸위기', '소멸위기', '소멸위기', '소멸위기', '소멸위기', '소멸위기',
       '소멸위기', '소멸진행', '위험없음', '양호', '소멸경고', '소멸경고', '소멸경고', '소멸경고',
       '소멸경고', '소멸위기', '소멸위기', '소멸위기', '소멸위기', '소멸위기', '소멸위기', '소멸위기',
       '소멸위기', '소멸위기', '소멸진행', '위험없음', '양호', '소멸경고', '소멸경고', '소멸경고',
       '소멸경고', '소멸경고', '소멸위기', '소멸위기', '소멸위기', '소멸위기', '소멸위기', '소멸위기',
       '소멸위기', '소멸위기', '소멸위기', '소멸진행', '위험없음', '양호', '소멸경고', '소멸경고',
       '소멸경고', '소멸경고', '소멸경고', '소멸위기', '소멸위기', '소멸위기', '소멸위기', '소멸위기',
       '소멸위기', '소멸위기', '소멸위기', '소멸위기', '소멸진행', '위험없음', '양호', '소멸경고',
       '소멸경고', '소멸경고', '소멸경고', '소멸경고', '소멸위기', '소멸위기', '소멸위기', '소멸위기',
       '소멸위기', '소멸위기', '소멸위기', '소멸위기', '소멸위기', '소멸진행', '위험없음', '양호',
       '소멸경고', '소멸경고', '소멸경고', '소멸경고', '소멸경고', '소멸위기', '소멸위기', '소멸위기',
       '소멸위기', '소멸위기

> test train 분리

In [37]:
from sklearn.model_selection import train_test_split
train_input, test_input, train_target, test_target =\
    train_test_split(fish_input,fish_target,random_state=42)

> 표준화

In [38]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(train_input)
train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)

---
### 로지스틱 회귀로 다중 분류 수행하기

In [39]:
# 로지스틱 회귀 실행하기
from sklearn.linear_model import LogisticRegression

lr=LogisticRegression()

lr = LogisticRegression(C=20, max_iter=1000)
lr.fit(train_scaled,train_target)
print("Train :", lr.score(train_scaled,train_target))
print("Test :", lr.score(test_scaled,test_target))

Train : 1.0
Test : 1.0


In [40]:
# test data로 예측
lr.predict(test_scaled[:5])

array(['소멸경고', '소멸위기', '소멸위기', '소멸위기', '소멸위기'], dtype=object)

In [41]:
# test data로 확률
proba = lr.predict_proba(test_scaled[:5])
np.round(proba, decimals=3)

array([[0.891, 0.106, 0.002, 0.   , 0.   ],
       [0.002, 0.996, 0.003, 0.   , 0.   ],
       [0.029, 0.968, 0.004, 0.   , 0.   ],
       [0.008, 0.986, 0.006, 0.   , 0.   ],
       [0.04 , 0.958, 0.002, 0.   , 0.   ]])

In [42]:
lr.classes_

array(['소멸경고', '소멸위기', '소멸진행', '양호', '위험없음'], dtype=object)

In [43]:
# 사용된 다중 공식 확인
print(lr.coef_, lr.intercept_)

[[ 2.97977446  0.87110328  0.65271374  1.64312495  0.65833326  0.90367854
  -0.12220532  0.98189876]
 [-3.70572964 -1.94483607 -1.80063909 -2.89258705 -1.39835992 -1.99445755
  -1.74252606 -6.39249425]
 [-2.34888953 -2.08614815 -2.00956359 -1.91117829 -2.3132508  -2.03361426
  -0.92700066  3.63269787]
 [ 1.17372345  1.37133962  1.30173736  1.93485125  0.8860586   1.38368025
   1.78763189  2.11240629]
 [ 1.90112126  1.78854133  1.85575157  1.22578915  2.16721885  1.74071302
   1.00410016 -0.33450868]] [ 6.02891746 -1.27705913 -2.89092024 -0.69373879 -1.1671993 ]


---
### 확률 분포 검증

In [44]:
decisions = lr.decision_function(test_scaled[:5])
np.round(decisions, decimals=2)

array([[ 4.75,  2.62, -1.29, -3.  , -3.08],
       [ 2.01,  8.49,  2.59, -6.26, -6.82],
       [ 3.  ,  6.52,  0.95, -5.04, -5.44],
       [ 2.46,  7.26,  2.13, -5.74, -6.11],
       [ 3.17,  6.35,  0.37, -4.87, -5.02]])

In [45]:
from scipy.special import softmax
proba = softmax(decisions, axis=1)
np.round(proba, decimals=3)

array([[0.891, 0.106, 0.002, 0.   , 0.   ],
       [0.002, 0.996, 0.003, 0.   , 0.   ],
       [0.029, 0.968, 0.004, 0.   , 0.   ],
       [0.008, 0.986, 0.006, 0.   , 0.   ],
       [0.04 , 0.958, 0.002, 0.   , 0.   ]])

In [46]:
lr.classes_

array(['소멸경고', '소멸위기', '소멸진행', '양호', '위험없음'], dtype=object)